name: Chinnachammagari Rajesh

on:
  push:
    branches: [main]

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: echo "Hello This is my first workflow"
   

  
